# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ellipse_plot.ui'
#
# Created: Sun Nov  9 16:03:05 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName(_fromUtf8("MplMainWindow"))
        MplMainWindow.resize(828, 639)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MplMainWindow.sizePolicy().hasHeightForWidth())
        MplMainWindow.setSizePolicy(sizePolicy)
        self.mplcentralwidget = QtGui.QWidget(MplMainWindow)
        self.mplcentralwidget.setObjectName(_fromUtf8("mplcentralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mplcentralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mpl_1 = MplWidget(self.mplcentralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_1.sizePolicy().hasHeightForWidth())
        self.mpl_1.setSizePolicy(sizePolicy)
        self.mpl_1.setObjectName(_fromUtf8("mpl_1"))
        self.verticalLayout.addWidget(self.mpl_1)
        self.horizontalGroupBox = QtGui.QGroupBox(self.mplcentralwidget)
        self.horizontalGroupBox.setFlat(True)
        self.horizontalGroupBox.setCheckable(False)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalGroupBox1 = QtGui.QGroupBox(self.horizontalGroupBox)
        self.horizontalGroupBox1.setObjectName(_fromUtf8("horizontalGroupBox1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.horizontalGroupBox1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.qwpLineEdit = QtGui.QLineEdit(self.horizontalGroupBox1)
        self.qwpLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.qwpLineEdit.setObjectName(_fromUtf8("qwpLineEdit"))
        self.horizontalLayout_4.addWidget(self.qwpLineEdit)
        self.horizontalLayout_3.addWidget(self.horizontalGroupBox1)
        self.gridGroupBox = QtGui.QGroupBox(self.horizontalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gridGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.gridGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.polLineEdit = QtGui.QLineEdit(self.gridGroupBox)
        self.polLineEdit.setInputMask(_fromUtf8(""))
        self.polLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.polLineEdit.setObjectName(_fromUtf8("polLineEdit"))
        self.horizontalLayout.addWidget(self.polLineEdit)
        self.horizontalLayout_3.addWidget(self.gridGroupBox)
        self.generateButton = QtGui.QPushButton(self.horizontalGroupBox)
        self.generateButton.setAcceptDrops(False)
        self.generateButton.setCheckable(False)
        self.generateButton.setAutoDefault(False)
        self.generateButton.setDefault(False)
        self.generateButton.setFlat(False)
        self.generateButton.setObjectName(_fromUtf8("generateButton"))
        self.horizontalLayout_3.addWidget(self.generateButton)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.horizontalGroupBox2 = QtGui.QGroupBox(self.mplcentralwidget)
        self.horizontalGroupBox2.setFlat(True)
        self.horizontalGroupBox2.setObjectName(_fromUtf8("horizontalGroupBox2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalGroupBox2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.jonesGroupBox = QtGui.QGroupBox(self.horizontalGroupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jonesGroupBox.sizePolicy().hasHeightForWidth())
        self.jonesGroupBox.setSizePolicy(sizePolicy)
        self.jonesGroupBox.setFlat(False)
        self.jonesGroupBox.setCheckable(True)
        self.jonesGroupBox.setChecked(False)
        self.jonesGroupBox.setObjectName(_fromUtf8("jonesGroupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.jonesGroupBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalFrame = QtGui.QFrame(self.jonesGroupBox)
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.verticalFrame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_6 = QtGui.QLabel(self.verticalFrame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.verticalFrame)
        self.verticalGroupBox = QtGui.QGroupBox(self.jonesGroupBox)
        self.verticalGroupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(38)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setFlat(True)
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.PsiLineEdit = QtGui.QLineEdit(self.verticalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PsiLineEdit.sizePolicy().hasHeightForWidth())
        self.PsiLineEdit.setSizePolicy(sizePolicy)
        self.PsiLineEdit.setObjectName(_fromUtf8("PsiLineEdit"))
        self.verticalLayout_2.addWidget(self.PsiLineEdit)
        self.deltaLineEdit = QtGui.QLineEdit(self.verticalGroupBox)
        self.deltaLineEdit.setObjectName(_fromUtf8("deltaLineEdit"))
        self.verticalLayout_2.addWidget(self.deltaLineEdit)
        self.horizontalLayout_5.addWidget(self.verticalGroupBox)
        self.jonesTranslatePushButton = QtGui.QPushButton(self.jonesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jonesTranslatePushButton.sizePolicy().hasHeightForWidth())
        self.jonesTranslatePushButton.setSizePolicy(sizePolicy)
        self.jonesTranslatePushButton.setObjectName(_fromUtf8("jonesTranslatePushButton"))
        self.horizontalLayout_5.addWidget(self.jonesTranslatePushButton)
        self.horizontalLayout_6.addWidget(self.jonesGroupBox)
        self.ellipticityGroupBox = QtGui.QGroupBox(self.horizontalGroupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipticityGroupBox.sizePolicy().hasHeightForWidth())
        self.ellipticityGroupBox.setSizePolicy(sizePolicy)
        self.ellipticityGroupBox.setFlat(False)
        self.ellipticityGroupBox.setCheckable(True)
        self.ellipticityGroupBox.setChecked(False)
        self.ellipticityGroupBox.setObjectName(_fromUtf8("ellipticityGroupBox"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.ellipticityGroupBox)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.ellipticityGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.directionLineEdit = QtGui.QLineEdit(self.ellipticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionLineEdit.sizePolicy().hasHeightForWidth())
        self.directionLineEdit.setSizePolicy(sizePolicy)
        self.directionLineEdit.setObjectName(_fromUtf8("directionLineEdit"))
        self.horizontalLayout_9.addWidget(self.directionLineEdit)
        self.label_4 = QtGui.QLabel(self.ellipticityGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.eangleLineEdit = QtGui.QLineEdit(self.ellipticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eangleLineEdit.sizePolicy().hasHeightForWidth())
        self.eangleLineEdit.setSizePolicy(sizePolicy)
        self.eangleLineEdit.setObjectName(_fromUtf8("eangleLineEdit"))
        self.horizontalLayout_9.addWidget(self.eangleLineEdit)
        self.ellipticityTranslatePushButton = QtGui.QPushButton(self.ellipticityGroupBox)
        self.ellipticityTranslatePushButton.setObjectName(_fromUtf8("ellipticityTranslatePushButton"))
        self.horizontalLayout_9.addWidget(self.ellipticityTranslatePushButton)
        self.horizontalLayout_6.addWidget(self.ellipticityGroupBox)
        self.verticalLayout.addWidget(self.horizontalGroupBox2)
        MplMainWindow.setCentralWidget(self.mplcentralwidget)
        self.menubar = QtGui.QMenuBar(MplMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MplMainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(MplMainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_Close = QtGui.QAction(MplMainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_About = QtGui.QAction(MplMainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menu_File.addAction(self.action_Close)
        self.menu_File.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MplMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "MainWindow", None))
        self.horizontalGroupBox.setTitle(_translate("MplMainWindow", "Controls", None))
        self.label_3.setText(_translate("MplMainWindow", "Quarter waveplate", None))
        self.qwpLineEdit.setText(_translate("MplMainWindow", "-pi/4", None))
        self.label.setText(_translate("MplMainWindow", "Polarizer", None))
        self.polLineEdit.setText(_translate("MplMainWindow", "-3*pi/8", None))
        self.generateButton.setText(_translate("MplMainWindow", "Generate", None))
        self.label_2.setText(_translate("MplMainWindow", "alpha", None))
        self.label_6.setText(_translate("MplMainWindow", "delta", None))
        self.jonesTranslatePushButton.setText(_translate("MplMainWindow", "Translate", None))
        self.label_5.setText(_translate("MplMainWindow", "Ellipse direction", None))
        self.label_4.setText(_translate("MplMainWindow", "Ellipticity angle", None))
        self.ellipticityTranslatePushButton.setText(_translate("MplMainWindow", "Translate", None))
        self.menu_File.setTitle(_translate("MplMainWindow", "Menu", None))
        self.action.setText(_translate("MplMainWindow", "About", None))
        self.action_Close.setText(_translate("MplMainWindow", "Close", None))
        self.action_About.setText(_translate("MplMainWindow", "About", None))

from mplwidget import MplWidget
