# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ellipse_plot.ui'
#
# Created: Tue Jan 27 12:01:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName("MplMainWindow")
        MplMainWindow.resize(828, 639)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MplMainWindow.sizePolicy().hasHeightForWidth())
        MplMainWindow.setSizePolicy(sizePolicy)
        self.mplcentralwidget = QtWidgets.QWidget(MplMainWindow)
        self.mplcentralwidget.setObjectName("mplcentralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mplcentralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl_1 = MplWidget(self.mplcentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_1.sizePolicy().hasHeightForWidth())
        self.mpl_1.setSizePolicy(sizePolicy)
        self.mpl_1.setObjectName("mpl_1")
        self.verticalLayout.addWidget(self.mpl_1)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.mplcentralwidget)
        self.horizontalGroupBox.setFlat(True)
        self.horizontalGroupBox.setCheckable(False)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalGroupBox1 = QtWidgets.QGroupBox(self.horizontalGroupBox)
        self.horizontalGroupBox1.setObjectName("horizontalGroupBox1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.horizontalGroupBox1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.qwpLineEdit = QtWidgets.QLineEdit(self.horizontalGroupBox1)
        self.qwpLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.qwpLineEdit.setObjectName("qwpLineEdit")
        self.horizontalLayout_4.addWidget(self.qwpLineEdit)
        self.horizontalLayout_3.addWidget(self.horizontalGroupBox1)
        self.gridGroupBox = QtWidgets.QGroupBox(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.gridGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.polLineEdit = QtWidgets.QLineEdit(self.gridGroupBox)
        self.polLineEdit.setInputMask("")
        self.polLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.polLineEdit.setObjectName("polLineEdit")
        self.horizontalLayout.addWidget(self.polLineEdit)
        self.horizontalLayout_3.addWidget(self.gridGroupBox)
        self.generateButton = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.generateButton.setAcceptDrops(False)
        self.generateButton.setCheckable(False)
        self.generateButton.setAutoDefault(False)
        self.generateButton.setDefault(False)
        self.generateButton.setFlat(False)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_3.addWidget(self.generateButton)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.horizontalGroupBox2 = QtWidgets.QGroupBox(self.mplcentralwidget)
        self.horizontalGroupBox2.setFlat(True)
        self.horizontalGroupBox2.setObjectName("horizontalGroupBox2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalGroupBox2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.jonesGroupBox = QtWidgets.QGroupBox(self.horizontalGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jonesGroupBox.sizePolicy().hasHeightForWidth())
        self.jonesGroupBox.setSizePolicy(sizePolicy)
        self.jonesGroupBox.setFlat(False)
        self.jonesGroupBox.setCheckable(True)
        self.jonesGroupBox.setChecked(False)
        self.jonesGroupBox.setObjectName("jonesGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.jonesGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalFrame = QtWidgets.QFrame(self.jonesGroupBox)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.verticalFrame)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.jonesGroupBox)
        self.verticalGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(38)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setFlat(True)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PsiLineEdit = QtWidgets.QLineEdit(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PsiLineEdit.sizePolicy().hasHeightForWidth())
        self.PsiLineEdit.setSizePolicy(sizePolicy)
        self.PsiLineEdit.setObjectName("PsiLineEdit")
        self.verticalLayout_2.addWidget(self.PsiLineEdit)
        self.deltaLineEdit = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.deltaLineEdit.setObjectName("deltaLineEdit")
        self.verticalLayout_2.addWidget(self.deltaLineEdit)
        self.horizontalLayout_5.addWidget(self.verticalGroupBox)
        self.jonesTranslatePushButton = QtWidgets.QPushButton(self.jonesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jonesTranslatePushButton.sizePolicy().hasHeightForWidth())
        self.jonesTranslatePushButton.setSizePolicy(sizePolicy)
        self.jonesTranslatePushButton.setObjectName("jonesTranslatePushButton")
        self.horizontalLayout_5.addWidget(self.jonesTranslatePushButton)
        self.horizontalLayout_6.addWidget(self.jonesGroupBox)
        self.ellipticityGroupBox = QtWidgets.QGroupBox(self.horizontalGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipticityGroupBox.sizePolicy().hasHeightForWidth())
        self.ellipticityGroupBox.setSizePolicy(sizePolicy)
        self.ellipticityGroupBox.setFlat(False)
        self.ellipticityGroupBox.setCheckable(True)
        self.ellipticityGroupBox.setChecked(False)
        self.ellipticityGroupBox.setObjectName("ellipticityGroupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.ellipticityGroupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.ellipticityGroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.directionLineEdit = QtWidgets.QLineEdit(self.ellipticityGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionLineEdit.sizePolicy().hasHeightForWidth())
        self.directionLineEdit.setSizePolicy(sizePolicy)
        self.directionLineEdit.setObjectName("directionLineEdit")
        self.horizontalLayout_9.addWidget(self.directionLineEdit)
        self.label_4 = QtWidgets.QLabel(self.ellipticityGroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.eangleLineEdit = QtWidgets.QLineEdit(self.ellipticityGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eangleLineEdit.sizePolicy().hasHeightForWidth())
        self.eangleLineEdit.setSizePolicy(sizePolicy)
        self.eangleLineEdit.setObjectName("eangleLineEdit")
        self.horizontalLayout_9.addWidget(self.eangleLineEdit)
        self.ellipticityTranslatePushButton = QtWidgets.QPushButton(self.ellipticityGroupBox)
        self.ellipticityTranslatePushButton.setObjectName("ellipticityTranslatePushButton")
        self.horizontalLayout_9.addWidget(self.ellipticityTranslatePushButton)
        self.horizontalLayout_6.addWidget(self.ellipticityGroupBox)
        self.verticalLayout.addWidget(self.horizontalGroupBox2)
        MplMainWindow.setCentralWidget(self.mplcentralwidget)
        self.menubar = QtWidgets.QMenuBar(MplMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MplMainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MplMainWindow)
        self.action.setObjectName("action")
        self.action_Close = QtWidgets.QAction(MplMainWindow)
        self.action_Close.setObjectName("action_Close")
        self.action_About = QtWidgets.QAction(MplMainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Documentation = QtWidgets.QAction(MplMainWindow)
        self.action_Documentation.setObjectName("action_Documentation")
        self.menu_File.addAction(self.action_Close)
        self.menu_File.addAction(self.action_About)
        self.menu_File.addAction(self.action_Documentation)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MplMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "MainWindow", None))
        self.horizontalGroupBox.setTitle(_translate("MplMainWindow", "Controls", None))
        self.label_3.setText(_translate("MplMainWindow", "Quarter waveplate", None))
        self.qwpLineEdit.setText(_translate("MplMainWindow", "-pi/4", None))
        self.label.setText(_translate("MplMainWindow", "Polarizer", None))
        self.polLineEdit.setText(_translate("MplMainWindow", "-3*pi/8", None))
        self.generateButton.setText(_translate("MplMainWindow", "Generate", None))
        self.label_2.setText(_translate("MplMainWindow", "alpha", None))
        self.label_6.setText(_translate("MplMainWindow", "delta", None))
        self.jonesTranslatePushButton.setText(_translate("MplMainWindow", "Translate", None))
        self.label_5.setText(_translate("MplMainWindow", "Ellipse direction", None))
        self.label_4.setText(_translate("MplMainWindow", "Ellipticity angle", None))
        self.ellipticityTranslatePushButton.setText(_translate("MplMainWindow", "Translate", None))
        self.menu_File.setTitle(_translate("MplMainWindow", "Menu", None))
        self.action.setText(_translate("MplMainWindow", "About", None))
        self.action_Close.setText(_translate("MplMainWindow", "Close", None))
        self.action_About.setText(_translate("MplMainWindow", "About", None))
        self.action_Documentation.setText(_translate("MplMainWindow", "Documentation", None))

from mplwidget import MplWidget

