# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propagator.ui'
#
# Created: Fri Oct 31 09:38:10 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(922, 608)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mpl_2 = MplWidget(self.horizontalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_2.sizePolicy().hasHeightForWidth())
        self.mpl_2.setSizePolicy(sizePolicy)
        self.mpl_2.setObjectName(_fromUtf8("mpl_2"))
        self.horizontalLayout.addWidget(self.mpl_2)
        self.verticalGroupBox = QtGui.QGroupBox(self.horizontalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setMinimumSize(QtCore.QSize(90, 0))
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_3.setContentsMargins(1, -1, 1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.propagate = QtGui.QPushButton(self.verticalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propagate.sizePolicy().hasHeightForWidth())
        self.propagate.setSizePolicy(sizePolicy)
        self.propagate.setObjectName(_fromUtf8("propagate"))
        self.verticalLayout_3.addWidget(self.propagate)
        self.Auto_Propagate_checkBox = QtGui.QCheckBox(self.verticalGroupBox)
        self.Auto_Propagate_checkBox.setObjectName(_fromUtf8("Auto_Propagate_checkBox"))
        self.verticalLayout_3.addWidget(self.Auto_Propagate_checkBox)
        self.horizontalLayout.addWidget(self.verticalGroupBox)
        self.mpl_1 = MplWidget(self.horizontalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_1.sizePolicy().hasHeightForWidth())
        self.mpl_1.setSizePolicy(sizePolicy)
        self.mpl_1.setObjectName(_fromUtf8("mpl_1"))
        self.horizontalLayout.addWidget(self.mpl_1)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.horizontalGroupBox_7 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_7.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_7.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalGroupBox_7.setTitle(_fromUtf8(""))
        self.horizontalGroupBox_7.setFlat(True)
        self.horizontalGroupBox_7.setObjectName(_fromUtf8("horizontalGroupBox_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalGroupBox_7)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalGroupBox1 = QtGui.QGroupBox(self.horizontalGroupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox1.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox1.setSizePolicy(sizePolicy)
        self.verticalGroupBox1.setObjectName(_fromUtf8("verticalGroupBox1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.verticalGroupBox1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.Jones_out_Y = QtGui.QLineEdit(self.verticalGroupBox1)
        self.Jones_out_Y.setObjectName(_fromUtf8("Jones_out_Y"))
        self.verticalLayout_2.addWidget(self.Jones_out_Y)
        self.label_4 = QtGui.QLabel(self.verticalGroupBox1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.Jones_out_X = QtGui.QLineEdit(self.verticalGroupBox1)
        self.Jones_out_X.setObjectName(_fromUtf8("Jones_out_X"))
        self.verticalLayout_2.addWidget(self.Jones_out_X)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox1)
        self.verticalGroupBox2 = QtGui.QGroupBox(self.horizontalGroupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox2.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox2.setSizePolicy(sizePolicy)
        self.verticalGroupBox2.setObjectName(_fromUtf8("verticalGroupBox2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridGroupBox = QtGui.QGroupBox(self.verticalGroupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setFlat(True)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalGroupBox_6 = QtGui.QGroupBox(self.gridGroupBox)
        self.horizontalGroupBox_6.setObjectName(_fromUtf8("horizontalGroupBox_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalGroupBox_6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.M_x2_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_6)
        self.M_x2_LineEdit.setObjectName(_fromUtf8("M_x2_LineEdit"))
        self.horizontalLayout_9.addWidget(self.M_x2_LineEdit)
        self.M_y2_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_6)
        self.M_y2_LineEdit.setObjectName(_fromUtf8("M_y2_LineEdit"))
        self.horizontalLayout_9.addWidget(self.M_y2_LineEdit)
        self.gridLayout.addWidget(self.horizontalGroupBox_6, 2, 2, 1, 1)
        self.horizontalGroupBox_5 = QtGui.QGroupBox(self.gridGroupBox)
        self.horizontalGroupBox_5.setObjectName(_fromUtf8("horizontalGroupBox_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalGroupBox_5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.M_z2_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_5)
        self.M_z2_LineEdit.setObjectName(_fromUtf8("M_z2_LineEdit"))
        self.horizontalLayout_8.addWidget(self.M_z2_LineEdit)
        self.M_w2_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_5)
        self.M_w2_LineEdit.setObjectName(_fromUtf8("M_w2_LineEdit"))
        self.horizontalLayout_8.addWidget(self.M_w2_LineEdit)
        self.gridLayout.addWidget(self.horizontalGroupBox_5, 2, 1, 1, 1)
        self.horizontalGroupBox_4 = QtGui.QGroupBox(self.gridGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_4.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_4.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_4.setObjectName(_fromUtf8("horizontalGroupBox_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalGroupBox_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.M_z1_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_4)
        self.M_z1_LineEdit.setObjectName(_fromUtf8("M_z1_LineEdit"))
        self.horizontalLayout_7.addWidget(self.M_z1_LineEdit)
        self.M_w1_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_4)
        self.M_w1_LineEdit.setObjectName(_fromUtf8("M_w1_LineEdit"))
        self.horizontalLayout_7.addWidget(self.M_w1_LineEdit)
        self.gridLayout.addWidget(self.horizontalGroupBox_4, 1, 2, 1, 1)
        self.horizontalGroupBox_3 = QtGui.QGroupBox(self.gridGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_3.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_3.setObjectName(_fromUtf8("horizontalGroupBox_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.M_x1_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_3)
        self.M_x1_LineEdit.setObjectName(_fromUtf8("M_x1_LineEdit"))
        self.horizontalLayout_5.addWidget(self.M_x1_LineEdit)
        self.M_y1_LineEdit = QtGui.QLineEdit(self.horizontalGroupBox_3)
        self.M_y1_LineEdit.setObjectName(_fromUtf8("M_y1_LineEdit"))
        self.horizontalLayout_5.addWidget(self.M_y1_LineEdit)
        self.gridLayout.addWidget(self.horizontalGroupBox_3, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.gridGroupBox)
        self.rawMatrix_checkBox = QtGui.QCheckBox(self.verticalGroupBox2)
        self.rawMatrix_checkBox.setObjectName(_fromUtf8("rawMatrix_checkBox"))
        self.verticalLayout_5.addWidget(self.rawMatrix_checkBox)
        self.raw_MatrixLineEdit = QtGui.QLineEdit(self.verticalGroupBox2)
        self.raw_MatrixLineEdit.setObjectName(_fromUtf8("raw_MatrixLineEdit"))
        self.verticalLayout_5.addWidget(self.raw_MatrixLineEdit)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox2)
        self.verticalGroupBox_3 = QtGui.QGroupBox(self.horizontalGroupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_3.setSizePolicy(sizePolicy)
        self.verticalGroupBox_3.setFlat(True)
        self.verticalGroupBox_3.setObjectName(_fromUtf8("verticalGroupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalGroupBox1 = QtGui.QGroupBox(self.verticalGroupBox_3)
        self.horizontalGroupBox1.setObjectName(_fromUtf8("horizontalGroupBox1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.horizontalGroupBox1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.directionLineEdit = QtGui.QLineEdit(self.horizontalGroupBox1)
        self.directionLineEdit.setObjectName(_fromUtf8("directionLineEdit"))
        self.horizontalLayout_3.addWidget(self.directionLineEdit)
        self.verticalLayout_4.addWidget(self.horizontalGroupBox1)
        self.directionSlider = QtGui.QSlider(self.verticalGroupBox_3)
        self.directionSlider.setMaximum(100)
        self.directionSlider.setProperty("value", 50)
        self.directionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.directionSlider.setObjectName(_fromUtf8("directionSlider"))
        self.verticalLayout_4.addWidget(self.directionSlider)
        self.horizontalGroupBox_2 = QtGui.QGroupBox(self.verticalGroupBox_3)
        self.horizontalGroupBox_2.setObjectName(_fromUtf8("horizontalGroupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.eangleLineEdit = QtGui.QLineEdit(self.horizontalGroupBox_2)
        self.eangleLineEdit.setObjectName(_fromUtf8("eangleLineEdit"))
        self.horizontalLayout_4.addWidget(self.eangleLineEdit)
        self.verticalLayout_4.addWidget(self.horizontalGroupBox_2)
        self.eangleSlider = QtGui.QSlider(self.verticalGroupBox_3)
        self.eangleSlider.setAccessibleName(_fromUtf8(""))
        self.eangleSlider.setMaximum(100)
        self.eangleSlider.setProperty("value", 50)
        self.eangleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.eangleSlider.setObjectName(_fromUtf8("eangleSlider"))
        self.verticalLayout_4.addWidget(self.eangleSlider)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox_3)
        self.verticalLayout.addWidget(self.horizontalGroupBox_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuMenu.addAction(self.action_Close)
        self.menuMenu.addAction(self.action_About)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.propagate.setText(_translate("MainWindow", "Propagate", None))
        self.Auto_Propagate_checkBox.setText(_translate("MainWindow", "Auto ", None))
        self.verticalGroupBox1.setTitle(_translate("MainWindow", "Output Jones Vector", None))
        self.label_3.setText(_translate("MainWindow", "Y component", None))
        self.label_4.setText(_translate("MainWindow", "X component", None))
        self.gridGroupBox.setTitle(_translate("MainWindow", "Jones matrix real elements of unknown object", None))
        self.M_x2_LineEdit.setText(_translate("MainWindow", "1/sqrt(2)", None))
        self.M_y2_LineEdit.setText(_translate("MainWindow", "-1/sqrt(2)", None))
        self.M_z2_LineEdit.setText(_translate("MainWindow", "0.", None))
        self.M_w2_LineEdit.setText(_translate("MainWindow", "0.", None))
        self.M_z1_LineEdit.setText(_translate("MainWindow", "0.", None))
        self.M_w1_LineEdit.setText(_translate("MainWindow", "0.", None))
        self.M_x1_LineEdit.setText(_translate("MainWindow", "1/sqrt(2)", None))
        self.M_y1_LineEdit.setText(_translate("MainWindow", "1/sqrt(2)", None))
        self.rawMatrix_checkBox.setText(_translate("MainWindow", "Raw input", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Ellipse </p><p>direction</p></body></html>", None))
        self.directionLineEdit.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "Ellipticity ", None))
        self.eangleLineEdit.setText(_translate("MainWindow", "0", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.action_Close.setText(_translate("MainWindow", "Action_Close", None))
        self.action_About.setText(_translate("MainWindow", "About", None))

from mplwidget import MplWidget
